In [5]:
import numpy as np
from sklearn.metrics import roc_curve
y = np.array([1,1,2,2])
sc=np.array([0.1,0.4,0.35,0.8])
fpr, tpr, th = roc_curve(y,sc,pos_label=2)#항목을 설정해줘야한다/auc는 roc하단의 넓이
fpr, tpr, th

(array([0. , 0. , 0.5, 0.5, 1. ]),
 array([0. , 0.5, 0.5, 1. , 1. ]),
 array([1.8 , 0.8 , 0.4 , 0.35, 0.1 ]))

In [6]:
from sklearn.metrics import auc#면적이기 때문의 가로와 세로 2가지가 존재
roc_auc=auc(fpr,tpr)
roc_auc

0.75