In [1]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

사전 기반 정수 인코딩

# 데이터 수집

In [2]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

데이터 전처리(문장 토큰화)

In [4]:
data1=sent_tokenize(text)
data1

['A barber is a person.',
 'a barber is good person.',
 'a barber is huge person.',
 'he Knew A Secret!',
 'The Secret He Kept is huge secret.',
 'Huge secret.',
 'His barber kept his word.',
 'a barber kept his word.',
 'His barber kept his secret.',
 'But keeping and keeping such a huge secret to himself was driving the barber crazy.',
 'the barber went up a huge mountain.']

데이터 전처리(단어 토큰화)

In [9]:
단어_모음={}
pr_data=[]
불용성단어= set(stopwords.words('english'))
for 문장 in data1:
    t_data=word_tokenize(문장)
    l=[]
    for 단어 in t_data:
        소문자_단어 = 단어.lower()#모든단어 소문자화
        if 소문자_단어 not in 불용성단어:
            if len(소문자_단어)>2:#단어수 2이하 제거
                l.append(소문자_단어)
                if 소문자_단어 not in 단어_모음:#단어모음안에 있는가 없는가
                    단어_모음[소문자_단어]=0
                단어_모음[소문자_단어]+=1
    pr_data.append(l)
pr_data  # 전저리된 data 비정형 data

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [10]:
단어_모음['barber']

8

In [12]:
정렬된_단어_모음=sorted(단어_모음.items(),key=lambda x:x[1],reverse=True)#정렬매소드, x는 튜플데이터
정렬된_단어_모음 #람다 일회성 함수 왼쪽 입력:오른쪽 함수

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [16]:
#인코딩이후 정형화를 해줘야한다.// 빈도수 높은애를 낮은정수로 만들어준다.
단어_인덱스={}
i=0
for (단어,빈도수) in 정렬된_단어_모음:
    if 빈도수 > 1 :#빈도수 1이하 제거
        i+=1
        단어_인덱스[단어]=i
단어_인덱스

{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'person': 5,
 'word': 6,
 'keeping': 7}

In [24]:
n=4
삭제_결정된_data=[단어 for 단어,i in 단어_인덱스.items() if i>n]
for i in 삭제_결정된_data:
    del 단어_인덱스[i]
단어_인덱스

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4}

In [27]:
단어_인덱스['OOV']=len(단어_인덱스)+1
단어_인덱스

{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'data': 5,
 '집합에 없는단어': 6,
 'OOV': 7}

In [28]:
#이제 정형화 =>정수로서 인코딩작업
ec_data=[]
for i in pr_data:
    ec_d=[]
    for 단어 in i:
        try:#예외발생시 에러가나면 except로 에러부분 점프
            ec_d.append(단어_인덱스[단어])
        except KeyError:
            ec_d.append(단어_인덱스['OOV'])
    ec_data.append(ec_d)
ec_data

[[1, 7],
 [1, 7, 7],
 [1, 3, 7],
 [7, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 7],
 [1, 4, 7],
 [1, 4, 2],
 [7, 7, 3, 2, 7, 1, 7],
 [1, 7, 3, 7]]

Counter 기반 정수 인코딩

In [29]:
from collections import Counter

In [30]:
pr_data

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [31]:
단어_모음집=sum(pr_data,[])
단어_모음집

['barber',
 'person',
 'barber',
 'good',
 'person',
 'barber',
 'huge',
 'person',
 'knew',
 'secret',
 'secret',
 'kept',
 'huge',
 'secret',
 'huge',
 'secret',
 'barber',
 'kept',
 'word',
 'barber',
 'kept',
 'word',
 'barber',
 'kept',
 'secret',
 'keeping',
 'keeping',
 'huge',
 'secret',
 'driving',
 'barber',
 'crazy',
 'barber',
 'went',
 'huge',
 'mountain']

In [33]:
결과_단어_모음집=Counter(단어_모음집)
type(결과_단어_모음집)
결과_단어_모음집

Counter({'barber': 8,
         'person': 3,
         'good': 1,
         'huge': 5,
         'knew': 1,
         'secret': 6,
         'kept': 4,
         'word': 2,
         'keeping': 2,
         'driving': 1,
         'crazy': 1,
         'went': 1,
         'mountain': 1})

In [34]:
n=4
빈도수별_단어=결과_단어_모음집.most_common(n)
빈도수별_단어

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4)]

In [35]:
단어_인덱스2={}
i=0
for 단어,빈도수 in 빈도수별_단어:
    i+=1
    단어_인덱스2[단어]=i
단어_인덱스2

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4}

In [36]:
단어_인덱스2['OOV']=len(단어_인덱스2)+1
단어_인덱스2

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'OOV': 5}

In [38]:
ec_data2=[]
for i in pr_data:
    ec_d2=[]
    for 단어 in i:
        try:#예외발생시 에러가나면 except로 에러부분 점프
            ec_d2.append(단어_인덱스2[단어])
        except KeyError:
            ec_d2.append(단어_인덱스2['OOV'])
    ec_data2.append(ec_d2)
ec_data2

[[1, 5],
 [1, 5, 5],
 [1, 3, 5],
 [5, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 5],
 [1, 4, 5],
 [1, 4, 2],
 [5, 5, 3, 2, 5, 1, 5],
 [1, 5, 3, 5]]

NLTk 정수 인코딩

In [42]:
from nltk import FreqDist
import numpy as np

In [45]:
단어_모음=FreqDist(np.hstack(pr_data))#대괄호깨기
단어_모음

FreqDist({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, ...})

In [46]:
단어_모음=단어_모음.most_common(4)
단어_모음

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4)]

케라스 이용data 토큰화 및 정수 인코딩

In [47]:
from tensorflow.keras.preprocessing.text import Tokenizer
pr_data

[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [49]:
ck_t=Tokenizer()
ck_t.fit_on_texts(pr_data)#텍스트가 얼마나 있는지 확인
ck_t.word_index
ck_t.word_counts

OrderedDict([('barber', 8),
             ('person', 3),
             ('good', 1),
             ('huge', 5),
             ('knew', 1),
             ('secret', 6),
             ('kept', 4),
             ('word', 2),
             ('keeping', 2),
             ('driving', 1),
             ('crazy', 1),
             ('went', 1),
             ('mountain', 1)])

In [64]:
encoded=ck_t.texts_to_sequences(pr_data)
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [62]:
n=4
end_ck=Tokenizer(num_words=n+2,oov_token='OOV')
end_ck.fit_on_texts(pr_data)
end_ck.texts_to_sequences(pr_data)

[[2, 1],
 [2, 1, 1],
 [2, 4, 1],
 [1, 3],
 [3, 5, 4, 3],
 [4, 3],
 [2, 5, 1],
 [2, 5, 1],
 [2, 5, 3],
 [1, 1, 4, 3, 1, 2, 1],
 [2, 1, 4, 1]]

In [65]:
max_l=max(len(x)for x in encoded)
max_l

7

In [67]:
for i in encoded:
    while len(i)<max_l:
        i.append(0)
data=np.array(encoded)
data

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [68]:
from tensorflow.keras.preprocessing.sequence import pad_sequences #크기요소 정리
ck_t=Tokenizer()
ck_t.fit_on_texts(pr_data)
encoded=ck_t.texts_to_sequences(pr_data)
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [70]:
end_data=pad_sequences(encoded,padding='post')#post 안단 구성요소 뒷단에 데이터값
end_data

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [72]:
end_data=pad_sequences(encoded,padding='post',truncating='post',maxlen=5)#post 안단 구성요소 뒷단에 데이터값
end_data

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]])

In [73]:
encoded

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [78]:
v=len(ck_t.word_index)+1
end_data=pad_sequences(encoded,padding='post',truncating='post',value=v)
end_data

array([[ 1,  5, 14, 14, 14, 14, 14],
       [ 1,  8,  5, 14, 14, 14, 14],
       [ 1,  3,  5, 14, 14, 14, 14],
       [ 9,  2, 14, 14, 14, 14, 14],
       [ 2,  4,  3,  2, 14, 14, 14],
       [ 3,  2, 14, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  2, 14, 14, 14, 14],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14, 14, 14]])

In [ ]:
#원핫인코딩은 차원이 높아지면 오버피팅 확률 높다
