In [53]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten, Embedding

# 1. 주어진 문장을 '단어'로 토큰화 하기

In [54]:
# 케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러 옵니다.
from tensorflow.keras.preprocessing.text import text_to_word_sequence
 
# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화 합니다.
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result) 


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [55]:
# 단어 빈도수 세기

# 세 개의 문장을 정의합니다.
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 토큰화 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.',
       ]

docs

['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
 '텍스트의 단어로 토큰화 해야 딥러닝에서 토큰화 인식됩니다.',
 '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.']

In [56]:
# 토큰화 함수를 이용해 전처리 하는 과정
from tensorflow.keras.preprocessing.text import Tokenizer

token = Tokenizer()             # 토큰화 함수 지정
token.fit_on_texts(docs)        # 토큰화 함수에 문장 적용

token

In [57]:
# 각 단어 빈도수 : .word_counts
print("\n단어 카운트:\n", token.word_counts) 
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict클래스를 사용합니다.


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 4), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])


In [58]:
# 총 문장 수 : .document_count
print("\n문장 카운트: ", token.document_count)


문장 카운트:  3


In [59]:
# 각 단어가 몇개의 문장에 포함되어 있는가 : .word_docs
# 출력되는 순서는 랜덤
print("\n각 단어가 몇개의 문장에 포함되어 있는가:\n", token.word_docs)


각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'토큰화': 3, '텍스트의': 2, '먼저': 1, '합니다': 1, '각': 1, '나누어': 1, '단어를': 1, '해야': 1, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '한': 1, '있습니다': 1, '결과는': 1, '수': 1, '할': 1, '사용': 1})


In [33]:
# 각 단어에 매겨진 인덱스 값 : .word_index
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index)


각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


# 2. 리뷰 감성분석 딥러닝 모델

In [60]:
# 텍스트 리뷰 10개를 정의합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","글쎄요 재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [61]:
# 토큰화 
from tensorflow.keras.preprocessing.text import Tokenizer

token = Tokenizer()
token.fit_on_texts(docs)

token

In [62]:
# 단어 별 빈도 수 계산
token.word_counts

OrderedDict([('너무', 1),
             ('재밌네요', 1),
             ('최고예요', 1),
             ('참', 1),
             ('잘', 1),
             ('만든', 1),
             ('영화예요', 1),
             ('추천하고', 1),
             ('싶은', 1),
             ('영화입니다', 1),
             ('한번', 1),
             ('더', 1),
             ('보고싶네요', 1),
             ('글쎄요', 2),
             ('별로예요', 1),
             ('생각보다', 1),
             ('지루하네요', 1),
             ('연기가', 1),
             ('어색해요', 1),
             ('재미없어요', 1)])

In [63]:
# 각 단어에 매겨진 인덱스 값
print(len(token.word_index))
print(token.word_index)

20
{'글쎄요': 1, '너무': 2, '재밌네요': 3, '최고예요': 4, '참': 5, '잘': 6, '만든': 7, '영화예요': 8, '추천하고': 9, '싶은': 10, '영화입니다': 11, '한번': 12, '더': 13, '보고싶네요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [64]:
# 문장 별 토큰화 결과 확인
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)


리뷰 텍스트, 토큰화 결과:
 [[2, 3], [4], [5, 6, 7, 8], [9, 10, 11], [12, 13, 14], [1], [15], [16, 17], [18, 19], [1, 20]]


In [65]:
# 문장 최대 길이 확인
len_list = []
for i in range(len(x)):
    len_list.append(len(x[i]))

print("문장 별 길이:", len_list)
print("문장 최대 길이:", np.max(len_list))

문장 별 길이: [2, 1, 4, 3, 3, 1, 1, 2, 2, 2]
문장 최대 길이: 4


In [66]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4) 
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  2  3]
 [ 0  0  0  4]
 [ 5  6  7  8]
 [ 0  9 10 11]
 [ 0 12 13 14]
 [ 0  0  0  1]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  1 20]]


### 테스트 데이터 만들기

In [67]:
test_docs = ["영화 재밌네요","올해 영화 중 최고예요","참 잘 만든 영화예요","추천하고 싶지 않은 영화입니다","두번 더 보고싶네요","글쎄요","아주 별로예요","생각보다 재미없네요","배우 연기가 어색해요","글쎄요 재미없어요"]

In [68]:
classes_test = array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [69]:
# 토큰화 
from tensorflow.keras.preprocessing.text import Tokenizer
token_test = Tokenizer()
token_test.fit_on_texts(test_docs)
token_test

In [70]:
# 각 단어에 매겨진 인덱스 값
print(len(token_test.word_index))
print(token_test.word_index)

25
{'영화': 1, '글쎄요': 2, '재밌네요': 3, '올해': 4, '중': 5, '최고예요': 6, '참': 7, '잘': 8, '만든': 9, '영화예요': 10, '추천하고': 11, '싶지': 12, '않은': 13, '영화입니다': 14, '두번': 15, '더': 16, '보고싶네요': 17, '아주': 18, '별로예요': 19, '생각보다': 20, '재미없네요': 21, '배우': 22, '연기가': 23, '어색해요': 24, '재미없어요': 25}


In [71]:
# 문장 별 토큰화 결과 확인
test_x = token_test.texts_to_sequences(test_docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  test_x)


리뷰 텍스트, 토큰화 결과:
 [[1, 3], [4, 1, 5, 6], [7, 8, 9, 10], [11, 12, 13, 14], [15, 16, 17], [2], [18, 19], [20, 21], [22, 23, 24], [2, 25]]


In [72]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
test_padded_x = pad_sequences(test_x, 4)  
print("\n패딩 결과:\n", test_padded_x) 


패딩 결과:
 [[ 0  0  1  3]
 [ 4  1  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [ 0 15 16 17]
 [ 0  0  0  2]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0 22 23 24]
 [ 0  0  2 25]]


### 딥러닝 모델

In [73]:
# 임베딩에 입력될 단어의 수를 지정합니다.(패딩 0까지 단어로 포함하기 위해 1을 더한다.)
word_size = len(token.word_index) + 1
word_size

21

In [74]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()

# (임베딩 층) 입력 벡터 크기: 단어 인덱스 수(21), 출력 벡터 크기: 10(수정 가능), 텍스트 패딩 결과인 4개씩 단어 입력
model.add(Embedding(21, 10, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))  # 이진 분류(긍정/부정)

# 모델 컴파일
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [75]:
# 모델 학습 : 데이터로 패딩된 피처(padded_x)와 클래스를 넣어준다.
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 871us/step - loss: 0.6876 - accuracy: 0.8000
Epoch 2/20
1/1 [==============================] - 0s 770us/step - loss: 0.6852 - accuracy: 0.8000
Epoch 3/20
1/1 [==============================] - 0s 621us/step - loss: 0.6827 - accuracy: 0.8000
Epoch 4/20
1/1 [==============================] - 0s 639us/step - loss: 0.6803 - accuracy: 0.9000
Epoch 5/20
1/1 [==============================] - 0s 702us/step - loss: 0.6779 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6754 - accuracy: 1.0000
Epoch 7/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6730 - accuracy: 1.0000
Epoch 8/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6705 - accuracy: 1.0000
Epoch 9/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6681 - accuracy: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6656 - accuracy: 1.0000
Epoch 11/20
1/1 [============

In [76]:
model.metrics_names

['loss', 'accuracy']

In [82]:
model.evaluate(test_padded_x, classes_test)[1]

InvalidArgumentError:  indices[7,3] = 21 is not in [0, 21)
	 [[node sequential_1/embedding_1/embedding_lookup (defined at <ipython-input-77-61add15fa9ed>:1) ]] [Op:__inference_test_function_2179]

Errors may have originated from an input operation.
Input Source operations connected to node sequential_1/embedding_1/embedding_lookup:
 sequential_1/embedding_1/embedding_lookup/2103 (defined at /Users/aiden/opt/anaconda3/lib/python3.7/contextlib.py:112)

Function call stack:
test_function


In [78]:
model.predict(padded_x)

array([[0.5307486 ],
       [0.5006423 ],
       [0.55491483],
       [0.5250013 ],
       [0.5287794 ],
       [0.48014086],
       [0.47679362],
       [0.46580243],
       [0.46549398],
       [0.46709713]], dtype=float32)