In [1]:
A=set([1,2,3,4,5])
B=set([4,5,6,7])
A | B #합집합


{1, 2, 3, 4, 5, 6, 7}

In [2]:
A=set([1,2,3,4,5])
B=set([4,5,6,7])
A & B

{4, 5}

In [3]:
data1='안녕 나는 오늘 힘들어'.split()
data2='안녕 못해 나는 지금 너무 힘들어'.split()
data1

['안녕', '나는', '오늘', '힘들어']

In [4]:
un=set(data1) | set(data2)
un

{'나는', '너무', '못해', '안녕', '오늘', '지금', '힘들어'}

In [5]:
intd = set(data1) & set(data2)
intd

{'나는', '안녕', '힘들어'}

In [6]:
len(intd)/len(un) #유사도 계산 자카드 유사도

0.42857142857142855

In [9]:
data1='안녕 나는 오늘 힘들어.'
data2='안녕 못해 나는 지금 너무 힘들어'

In [10]:
all_data=data1 +'  '+data2
all_data

'안녕 나는 오늘 힘들어.  안녕 못해 나는 지금 너무 힘들어'

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
t_v=TfidfVectorizer()
m_data=t_v.fit_transform([data1,data2])
m_data.toarray()

array([[0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087],
       [0.33471228, 0.47042643, 0.47042643, 0.33471228, 0.        ,
        0.47042643, 0.33471228]])

In [14]:
t_v.vocabulary_

{'안녕': 3, '나는': 0, '오늘': 4, '힘들어': 6, '못해': 2, '지금': 5, '너무': 1}

In [13]:
idf=t_v.idf_#있냐 없냐 유무를 알려줌

array([1.        , 1.40546511, 1.40546511, 1.        , 1.40546511,
       1.40546511, 1.        ])

In [15]:
m_data[0:1].toarray()

array([[0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087]])

In [18]:
from sklearn.metrics import jaccard_score
import numpy as np
jaccard_score(np.array([0,1,0,0]),np.array([0,1,1,2]),average=None)

array([0.33333333, 0.5       , 0.        ])

In [23]:
def f(A,B):
    return np.sqrt(np.sum((A-B)**2))#sqre 루트,넘파이 어레이는 각각 길이가 같은것들은 계산된다.

In [24]:
A=np.array([0,1,2,3,4])
B=np.array([1,0,1,2,3])
f(A,B)

2.23606797749979

유클리드 거리 유사도 확인

In [25]:
from sklearn.metrics import euclidean_distances
euclidean_distances(m_data[0:1],m_data[1:2])

array([[1.0486415]])

In [26]:
m_data.toarray()

array([[0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087],
       [0.33471228, 0.47042643, 0.47042643, 0.33471228, 0.        ,
        0.47042643, 0.33471228]])

In [27]:
def e_f(m):
    return m/np.sum(m) #정규화작업

In [31]:
e_data=e_f(m_data).toarray()

In [32]:
euclidean_distances(e_data[0:1],e_data[1:2])

array([[0.23884449]])

In [38]:
a=np.array([-1,2,3])
b=np.array([1,3,-4])
def f(A,B):
    return np.sum(abs((A-B)))
#abs(a-b)#절댓값

In [39]:
A=np.array([0,1,2,3,4])
B=np.array([1,0,1,2,3])
f(A,B)#수치값이 낮을수록 좋다

5

맨하탄 거리 유사도 확인

In [41]:
from sklearn.metrics.pairwise import manhattan_distances
manhattan_distances(m_data[0:1],m_data[1:2])

array([[2.38220441]])

정규화된 data를 이용하여 유사도 계산

In [42]:
manhattan_distances(e_data[0:1],e_data[1:2])

array([[0.54258429]])

In [43]:
euclidean_distances(e_data[0:1],e_data[1:2])

array([[0.23884449]])

In [44]:
data1='안녕 나는 오늘 힘들어.'
data2='안녕 못해 나는 지금 너무 힘들어'
data3='나는 너무 즐거워'
m_data=t_v.fit_transform([data1,data2,data3])

In [49]:
#정규화
def e_f(m):
    return m/np.sum(m)
e_data=e_f(m_data)

In [56]:
ck1=euclidean_distances(m_data[0:1],m_data[1:2])
ck2=euclidean_distances(m_data[1:2],m_data[2:3])
ck1,ck2,ck1-ck2

(array([[1.02891385]]), array([[1.15714912]]), array([[-0.12823528]]))

In [57]:
ck1=ck1/ck1
ck2=ck2/ck1
ck1,ck2#정규화 하지 않은데이터

(array([[1.]]), array([[1.15714912]]))

In [58]:
e_ck1=euclidean_distances(e_data[0:1],e_data[1:2])
e_ck2=euclidean_distances(e_data[1:2],e_data[2:3])
e_ck1,e_ck2,e_ck1-e_ck2

(array([[0.16949987]]), array([[0.19062493]]), array([[-0.02112506]]))

In [59]:
e_ck1=e_ck1/e_ck1
e_ck2=e_ck2/e_ck1
e_ck1,e_ck2#정규화를 한 데이터

(array([[1.]]), array([[0.19062493]]))

In [61]:
abs(ck1-ck2),abs(e_ck1-e_ck2) # => 유사성 판명도에는 명확하게 만들어주는게 정규화 작업이다. 0.15<<<0.809

(array([[0.15714912]]), array([[0.80937507]]))

In [54]:
manhattan_distances(m_data[0:1],m_data[1:2]),manhattan_distances(m_data[1:2],m_data[2:3])

(array([[2.28685493]]), array([[2.76734191]]))

In [55]:
manhattan_distances(e_data[0:1],e_data[1:2]),manhattan_distances(e_data[1:2],e_data[2:3])

(array([[0.37672893]]), array([[0.45588277]]))

In [63]:
ck1=euclidean_distances(m_data[0:1],m_data[1:2])
ck2=euclidean_distances(m_data[1:2],m_data[2:3])
ck1=ck1/ck1
ck2=ck2/ck1
e_ck1=euclidean_distances(e_data[0:1],e_data[1:2])
e_ck2=euclidean_distances(e_data[1:2],e_data[2:3])
e_ck1=e_ck1/e_ck1
e_ck2=e_ck2/e_ck1
print("유클리드 거리를 이용한 계산")
print(f'정규화 전 data이용 거리 계산{abs(ck1-ck2)}')
print(f'정규화 후 data이용 거리 계산{abs(e_ck1-e_ck2)}')

유클리드 거리를 이용한 계산
정규화 전 data이용 거리 계산[[0.15714912]]
정규화 후 data이용 거리 계산[[0.80937507]]


In [64]:
ck1=manhattan_distances(m_data[0:1],m_data[1:2])
ck2=manhattan_distances(m_data[1:2],m_data[2:3])
ck1=ck1/ck1
ck2=ck2/ck1
e_ck1=manhattan_distances(e_data[0:1],e_data[1:2])
e_ck2=manhattan_distances(e_data[1:2],e_data[2:3])
e_ck1=e_ck1/e_ck1
e_ck2=e_ck2/e_ck1
print("맨하탄 거리를 이용한 계산")
print(f'정규화 전 data이용 거리 계산{abs(ck1-ck2)}')
print(f'정규화 후 data이용 거리 계산{abs(e_ck1-e_ck2)}')

맨하탄 거리를 이용한 계산
정규화 전 data이용 거리 계산[[1.76734191]]
정규화 후 data이용 거리 계산[[0.54411723]]
