## 로지스틱 회귀 나누기 위해 분류하는 객체

In [1]:
import numpy as np #data 계산을 위한 모듈
import pandas as pd #data 로드를 위한 모듈
from sklearn.model_selection import train_test_split #학습 data와 테스트 data 분할 모듈
from sklearn.preprocessing import PolynomialFeatures #피처 증가를 위한 모듈
from sklearn.linear_model import LinearRegression ,Lasso, Ridge,SGDRegressor  # 선형 회귀 모듈
from sklearn.preprocessing import StandardScaler # data 전처리 (중복 정보 정리)->밸런싱 작업
import matplotlib.pyplot as plt # 시각화 모듈
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [55]:
data=pd.read_csv('data1_all.csv')
data

Name  Weight  Length  Diagonal   Height   Width
0      A   242.0    25.4      30.0  11.5200  4.0200
1      A   290.0    26.3      31.2  12.4800  4.3056
2      A   340.0    26.5      31.1  12.3778  4.6961
3      A   363.0    29.0      33.5  12.7300  4.4555
4      A   430.0    29.0      34.0  12.4440  5.1340
..   ...     ...     ...       ...      ...     ...
154    G    12.2    12.2      13.4   2.0904  1.3936
155    G    13.4    12.4      13.5   2.4300  1.2690
156    G    12.2    13.0      13.8   2.2770  1.2558
157    G    19.7    14.3      15.2   2.8728  2.0672
158    G    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 6 columns]

data수집

In [56]:
data_X=data[['Weight','Length','Diagonal','Height','Width']].to_numpy()
data_Y=data['Name'].to_numpy()

data 전처리

In [57]:
ss=StandardScaler().fit(data_X)
data_X=ss.transform(data_X)

입력data정리

In [58]:
t_x,tt_x,t_y,tt_y=train_test_split(data_X,data_Y,random_state=42)


모델 생성 및 학습

In [70]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=20,max_iter=1000)
lr.fit(t_x,t_y)#다중분류용
lr.score(t_x,t_y),lr.score(tt_x,tt_y)
d=lr.decision_function(b_t_x[:1])#다중분류에서 사용하는 함수 로지스틱함수에서 2가지존재한다
#from scipy.special import expit #2진분류는 시그노이드펑션
from scipy.special import softmax #2다중분류는 소프트맥스평선
np.round(softmax(d))

array([[1., 0., 0., 0., 0., 0., 0.]])

검증

In [60]:
lr.score(t_x,t_y),lr.score(tt_x,tt_y)

(0.9243697478991597, 0.925)

In [61]:
# z=np.arange(-5,5,0.1)
# h=1/(1+np.exp(-z))


In [62]:
# plt.plot(z,h)

In [63]:
# n_l=np.array(['a','b','c'])
# n_l[[True,False,True]]

In [64]:
i=(t_y =='A')|(t_y == 'G')
b_t_x=t_x[i]
b_t_y=t_y[i]
lr = LogisticRegression()
lr.fit(b_t_x,b_t_y)

LogisticRegression()

In [65]:
lr.coef_,lr.intercept_

(array([[-0.41981254, -0.60056128, -0.68786241, -1.00159093, -0.74532495]]),
 array([-2.1898649]))

In [66]:
d=lr.decision_function(b_t_x[:1])#학습된 공식을 꺼냄

In [67]:
from scipy.special import expit #역함수
expit(d)#a데이터다 b데이터다 하면서 나눠서 2분법으로 나타내는것
#2분나눠줘서 다중으로 나눠지는것이 안댐

array([0.00254817])